---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sentinel-readonly
  namespace: sentinel
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sentinel-readonly
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "daemonsets", "statefulsets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sentinel-readonly
subjects:
- kind: ServiceAccount
  name: sentinel-readonly
  namespace: sentinel
roleRef:
  kind: ClusterRole
  name: sentinel-readonly
  apiGroup: rbac.authorization.k8s.io
